### PR TITLE
Change WHERE clause to return false

### PR DESCRIPTION
**Pull request by dtseiler**
I'm assuming this is what you meant here.

### CODE REVIEW

**Comment by theory** [comment]
Nope. By making it `WHERE 1 = 1`, it should never scan any rows. If you make it `WHERE 0 = 1`, it will do a table scan. Since the whole point is to make sure the table exists with the expected columns, a table scan is unnecessary, so I avoid it.

**Comment by dtseiler** [comment]
Not quite sure I follow you. If you have WHERE 1=1, you're saying you want all the rows. Why wouldn't it then scan the table?

**Comment by theory** [comment]
Oh. Yeah, I'm an idiot, sorry.

**Comment by dtseiler** [comment]
No worries ;)

**Comment by dtseiler** [comment]
PS - I don't know if you have similar examples in the other tutorials that might need similar corrections. I'm an Oracle DBA so I was only reading that one.

**Comment by theory** [comment]
No, the others are able to use clearer expressions, like `WHERE FALSE`.

**Pull request merged**
